### ISSUE TITLE
Implement MAX_SIMULTANEOUS_NOTES define

### ISSUE THREAD

**Issue by MrComit** [HackerN64/HackerSM64#146]
When in the merry-go-round room in BBH on console, the game runs at around 23-24fps, and lower if fire is on screen.

**Comment by gheskett** [comment]
Merry-go-round seems to have a ton of audio lag. At some point I will create a define that limits the maximum note count, which will help account for demanding audio lag, particularly when using the EXPAND_AUDIO_HEAP define. This however will also cause abrupt audio cutoffs to be more frequent with lower values.

This feature will not be included in the current refactor, so I will remove it from the current project for now.
