### ISSUE TITLE
Considerable lag when displaying dialog

### ISSUE THREAD

**Issue by Mineqwerty** [HackerN64/HackerSM64#148]
On console, the game chugs during a few specific spots in the baby penguin mission in CCM. Talking to the mother drops the game to around 25 FPS. The star dance cutscene also has lag for some reason, dropping to around 27 FPS and delaying the "HERE WE GO!" voice clip past when it should play in the song.

**Comment by axollyon** [comment]
Can reproduce - talking to the mother on default settings actually dropped to a minimum of 20 fps. However, I did not get any lag on the star cutscene. Proposing that this issue be saved for 2.1, as it does not interfere with gameplay whatsoever, making it low priority.

**Comment by axollyon** [comment]
Did some more testing, found out that this is an issue with lag during dialog in general. Definitely save for 2.1.

**Comment by gheskett** [comment]
Is this something we can like, fix? The vanilla dialog system sucks but it pretty much needs an overhaul in order to see any real performance boost. I will move this to 2.2 but it's debatable as to whether this should just be closed and moved to a larger scale feature issue.

**Comment by thecozies** [comment]
@gheskett yeah that's a good point. maybe this is something to consider post-ascii conversion where we will have more control over the system

**Comment by gheskett** [comment]
Closing this, as it's no longer relevant.
