### ISSUE TITLE
Global variable increments

### ISSUE THREAD

**Issue by Mr-Wiseguy** [HackerN64/HackerSM64#154]
There are many instances of game code incrementing or otherwise changing global variables by one value at a time. This is most common with `gDisplayListHead` getting incremented in gbi macros. These cause the compiler to generate a lot of unnecessary loads and stores, which hurt performance and potentially even hurt memory bandwidth. These should be changed to copying the global into a local, working on the local, and then overwriting the global with the local's value at the end of the function.

**Comment by gheskett** [comment]
Moved to 2.2
