### ISSUE TITLE
Deprecate `sBackgroundMusicDefaultVolume` Table

### ISSUE THREAD

**Issue by gheskett** [HackerN64/HackerSM64#220]
Nintendo moment.

Slated for 2.0 rather than 2.1, as this will make it much easier for streamed tools to program this change in.

**Comment by gheskett** [comment]
Should I delete the table entirely or should I just mark it `UNUSED`? Leaving the table in is potentially a waste of data and code space, but removing it is a potential merge conflict for others (although not a particularly difficult one to fix probably),

**Comment by thecozies** [comment]
Adding @Mr-Wiseguy to the convo here

**Comment by thecozies** [comment]
Personally I'm in `fear change` mode and after all the testing we've done, it scares me to include something like this so late into this process. This upcoming week is going to be busy for many people (i'll be out friday through monday), and then we have only a few more days until 2022 (our 2.0 goal), so i feel like putting this through the proper hoops could either push us back, or not test as well and introduce unexpected bugs.

If we were to do this change, I think that it should be a "define in the file" for this release. this helps with multiple things:
- people upgrading have no conflicts here
- people who havent upgraded streamed audio tools are supported
- if theres an issue, its easy to define `USED_DEPRECATED_AUDIO_TABLE` or whatever it is and get the table back

**Comment by thecozies** [comment]
(then 2.1 deletes the table fully)

**Comment by axollyon** [comment]
I think this should be kept for 2.1, we don't have time to look for any potential bugs this might introduce now, no matter the benefit

**Comment by Mr-Wiseguy** [comment]
Agreed on waiting due to not having time to test for 2.0 without pushing back the release.
