### ISSUE TITLE
Exit Course Sound Effect Does Not Play

### ISSUE THREAD

**Issue by gheskett** [HackerN64/HackerSM64#286]
The sound effect that plays when exiting course and respawning in the castle simply does not activate. It doesn't play when voiding out of the vanish cap stage either.

**Comment by Arceveti** [comment]
This is because of the `ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS` check in `init_mario_after_warp`. It works fine when `ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS` is enabled.

**Comment by thecozies** [comment]
I'd say 2.1 or 2.2 but i agree
