### ISSUE TITLE
Defines for removing coin score and cap pos from the savefile

### ISSUE THREAD

**Issue by Reonu** [HackerN64/HackerSM64#317]
No one ever looks at coin score and cap pos is straight up unused in vanilla so they're good candidates for a savefile cleanup.

**Comment by Mineqwerty** [comment]
Isn’t this kinda define bloat for something that won’t matter to most people? (And if it does, it very likely won’t be hard for them to remove it themselves)

**Comment by gheskett** [comment]
Idk, they're referenced in a few annoying places too, but it would definitely be ifdef heavy to remove every tangible reference to cap logic

**Comment by Reonu** [comment]
I think we should forget about coin score and leave it alone, but we should remove capPos without a define or anything, just nuke it. It's literally unused, useless data that takes space in the savefile for no reason. No harm in removing it.

**Comment by gheskett** [comment]
Apparently cap pos is less useless than we thought, so we can't just remove it. I think there are better ways to increase save file storage space, so personally I don't think we should implement this.
