### ISSUE TITLE
discord is down

### ISSUE THREAD

**Issue by thecozies** [HackerN64/HackerSM64#340]
idk what to do

**Comment by Reonu** [comment]
@Arceveti what the fuck did you do this time

**Comment by thecozies** [comment]
some small optimizations 😔

**Comment by gheskett** [comment]
Huh, collaborators can no longer assign issues to projects or milestones.

That's...not ideal.

**Comment by thecozies** [comment]
@gheskett good find then, we should be able to fix that

**Comment by thecozies** [comment]
hmm maybe arctic isn't a maintainer?

**Comment by thecozies** [comment]
@gheskett try now

**Comment by gheskett** [comment]
Yup, works now I think

**Comment by thecozies** [comment]
# nice

we need to add everybody as collaborators again @Reonu

**Comment by gheskett** [comment]
Maybe it's because the projects are tied to the repo and not the org

**Comment by Reonu** [comment]
> 

wouldn't that give everyone write permissions? 

> # nice
> 
> we need to add everybody as collaborators again @Reonu

**Comment by thecozies** [comment]
ahhh collaborators we're added to the org? should be transferable

**Comment by thecozies** [comment]
> > 
> 
> wouldn't that give everyone write permissions?
> 
> > # nice
> > we need to add everybody as collaborators again @Reonu

ahh maybe we need to adjust the perms on that role then

**Comment by arthurtilly** [comment]
sup fuckos

**Comment by thecozies** [comment]
i think people need to be the triage role actually

# YO ARTHUR

**Comment by thecozies** [comment]
###### i wish discord had markdown too

**Comment by Reonu** [comment]
cum

**Comment by arthurtilly** [comment]
have we considered porting discord to pc port?

**Comment by thecozies** [comment]
> cum

wtf is that supposed to mean

**Comment by thecozies** [comment]
> have we considered porting discord to pc port?

no but let's open a new issue asap

**Comment by gheskett** [comment]
> ###### i wish discord had markdown too

Why even use Discord? Clearly this is the superior option.

**Comment by someone2639** [comment]
something something libera.chat #someone2639 is open (or you could also make a hacker64 channel i guess)

**Comment by thecozies** [comment]
i can't figure out how to libera.chat

**Comment by gheskett** [comment]
time to use Slack

**Comment by thecozies** [comment]
oh god

**Comment by someone2639** [comment]
libera.chat connect webchat #whatever_channel set username done

**Comment by thecozies** [comment]
it's not letting me 🤔

**Comment by gheskett** [comment]
> it's not letting me thinking

skill issue 😔

**Comment by someone2639** [comment]
![Screenshot_20220308-141125_Revolution IRC.jpg](https://user-images.githubusercontent.com/9752483/157308534-3100784d-253b-4b13-b6fc-f2048c7492e1.jpg)

if you have funny android you can get an irc app and connect to here and join the channel (i use revolution irc)

**Comment by gheskett** [comment]
That's too much effort.

Try `web.libera.chat`

**Comment by gheskett** [comment]
Wouldn't it be funny if we just left this issue open?

Not really to be honest.

**Comment by gheskett** [comment]
F

**Comment by gheskett** [comment]
ixed 😔
