### ISSUE TITLE
Convert vanilla text system to use ASCII

### ISSUE THREAD

**Issue by gheskett** [HackerN64/HackerSM64#342]
Because the current system is dumb and stupid and dumb

**Comment by Reonu** [comment]
if possible this should include support for accented characters while we're at it (like we could have a texture for `´` and if you type `á` the game knows to just draw the accent over the `a`)

**Comment by thecozies** [comment]
> if possible this should include support for accented characters while we're at it (like we could have a texture for `´` and if you type `á` the game knows to just draw the accent over the `a`)

yup, that'd be great

**Comment by axollyon** [comment]
@arthurtilly is also working on support for UTF-8 characters (see #449)
