### ISSUE TITLE
Speedrun timer integration

### ISSUE THREAD

**Issue by thecozies** [HackerN64/HackerSM64#343]
Important asks:
- track time during gameplay (and mario not in a cutscene state?)
- use a u32 so that it can be really really long
- cap the time at a reasonably high amount (like 20 hours or so)
- `eventually` add an function to save your best times
- add a function for formatting the time into a char buffer so it can be used anywhere
- add optional printing implementations:
    - ia4 text
    - puppyprint
    - NOT CLOWN FONT (takes up way too much space and its gross and i hate it) 
- BONUS:
    - way to toggle speedrun mode on the main menu 
    - **Do not save** while in speedrun mode, and dont ask >:( (only save the record time itself)

**Comment by gheskett** [comment]
> cap the time at a reasonably high amount (like 20 hours or so)

Any specific reason for this? I don't see why we couldn't just cap out at like 99 hours or something.

> use a u32 so that it can be really really long

If we're capping the timer anyway, this could probably fit into just 3 bytes. It might be slightly more painful to read or work with, but it could save significant space if we want to potentially save more than one time to the save file.

**Comment by gheskett** [comment]
Thinking this _might_ be scope creep, given how subjective the implementation for this might be. Granted most of the actual functionality itself would be valid, so I'll keep it open for now at least.

**Comment by arthurtilly** [comment]
i wouldnt be opposed to this if it was just a variable saved to the save file to be used at the hacker's discretion (if it is NOT a define), but i think adding functions specifically to print it is getting too far out of scope

**Comment by gheskett** [comment]
Eh, I'm gonna close this. There's way too much subjectivity when it comes to a speedrun timer and how it works or how it's used, so I don't know of a good way to implement it that isn't just covering global playtime, nor is there a great way of defining when to stop the timer etc. Not to mention, print functions for such a timer is really pushing it.
