### ISSUE TITLE
RCP is HUNG UP!! Oh! MY GOD!!

### ISSUE THREAD

**Issue by thecozies** [HackerN64/HackerSM64#344]
Add a way for RCP hang ups to be detected, and a good way of handling it too! This is how I'm currently doing it but maybe there's a better way to give the alert. Plus: what should we do if DEBUG isnt defined? @someone2639 added this assert function but when DEBUG isnt defined it won't do anything. So maybe it should be a force crash or an enforced assertion so that the game properly exits. Alternatively we could show a special crash screen in this case, and have it only display a message since this stack trace is pretty useless.

```c
s32 handle_wait_vblank(OSMesgQueue *mq) {
    // returns true if it lasts longer than 3 seconds (3 * 1000us * 1000ms)
    OSMesg msg;
    OSTimer timer;
    osSetTimer(&timer, OS_USEC_TO_CYCLES(3000000), 0, mq, (OSMesg)666);
    osRecvMesg(mq, &msg, OS_MESG_BLOCK);
    osStopTimer(&timer);

    return msg == (OSMesg)666;
}

static void rcp_omg(void) {
    osSyncPrintf("RCP is HUNG UP!! Oh! MY GOD!!");
    assert(FALSE, "RCP is HUNG UP!! Oh! MY GOD!!");
}

/**
 * This function:
 * - Sends the current master display list out to be rendered.
 * - Tells the VI which color framebuffer to be displayed.
 * - Yields to the VI framerate twice, locking the game at 30 FPS.
 * - Selects which framebuffer will be rendered and displayed to next time.
 */
void display_and_vsync(void) {
    if (handle_wait_vblank(&gGfxVblankQueue)) rcp_omg();

    if (gGoddardVblankCallback != NULL) {
        gGoddardVblankCallback();
        gGoddardVblankCallback = NULL;
    }
    exec_display_list(&gGfxPool->spTask);

    if (handle_wait_vblank(&gGameVblankQueue)) rcp_omg();

    osViSwapBuffer((void *) PHYSICAL_TO_VIRTUAL(gPhysicalFramebuffers[sRenderedFramebuffer]));

    if (handle_wait_vblank(&gGameVblankQueue)) rcp_omg();

    // Skip swapping buffers on emulator so that they display immediately as the Gfx task finishes
    if (gIsConsole || gIsVC) { // Read RDP Clock Register, has a value of zero on emulators
        if (++sRenderedFramebuffer == 3) {
            sRenderedFramebuffer = 0;
        }
        if (++sRenderingFramebuffer == 3) {
            sRenderingFramebuffer = 0;
        }
    }
    gGlobalTimer++;
}
```

**Comment by Reonu** [comment]
Oh! My GOD!!

**Comment by someone2639** [comment]
the crash screen interprets a syscall exception as a failed assert even if debug isn't defined, so some hardcoding can be done

**Comment by someone2639** [comment]
additionally, osSetTimer is how it's done in oot (function that sends a message if a certain number of cycles have passed) by checking whether the message received by the vblank queue was a certain magic value or not

**Comment by thecozies** [comment]
> additionally, osSetTimer is how it's done in oot (function that sends a message if a certain number of cycles have passed) by checking whether the message received by the vblank queue was a certain magic value or not

@someone2639 check my first message, i did that part and it seems to work well. 

___

> the crash screen interprets a syscall exception as a failed assert even if debug isn't defined, so some hardcoding can be done

yeah that works. i think it should be a reusable assert function though, like an assert that only displays your assert message (line/file would be cool info too). in #development we were talking about how warp misses should be an obvious message like this because its a very specific problem thats likely caused by one specific thing. so having the same functionality for those assertions would be very nifty

**Comment by someone2639** [comment]
> @someone2639 check my first message, i did that part and it seems to work well. 

oops i

forgot to read higher than the display_vsync


> having the same functionality for those assertions would be very nifty

we have some registers to spare with asserts, we could use them as an index to a table of common error strings

**Comment by thecozies** [comment]
yeah that seems like it could work! it'd be nice to have the message in place tho (like on that line itself) rather than in a separate file if thats possible.

**Comment by someone2639** [comment]
how to assign issue to myself 2019
