### ISSUE TITLE
EU Currently Doesn't Boot

### ISSUE THREAD

**Issue by gheskett** [HackerN64/HackerSM64#354]
EU builds but currently doesn't boot. Likely JP doesn't boot either and it's a near guarantee SH currently doesn't, but EU is the only one I would consider worth saving right now.

**Comment by gheskett** [comment]
^ This (currently unmerged at time of writing) is what allows EU to build, but it doesn't actually allow EU to boot.

**Comment by gheskett** [comment]
^ This (currently unmerged at time of writing) is what allows EU to build, but it doesn't actually allow EU to boot.

**Comment by gheskett** [comment]
At this point it's worth considering whether we should just completely scrap everything non-US. Audio stuff probably needs to be sorted through but everything else can probably go.

**Comment by arthurtilly** [comment]
all ifdefs have already been gone from ingame menu and file select for a while, multilang will completely remove dependence on VERSION_EU for support as well as not needing VERSION_JP anyway, so as long as the baserom extraction stuff stays (jp characters will obv depend on jp rom) i dont see much reason to keep version support. some ifdefs maybe should still stay tho so the code isnt lost

**Comment by gheskett** [comment]
At this point, we are pretty much committed to US only. This issue is no longer applicable.
