### ISSUE TITLE
Allow any number of red coins in a level

### ISSUE THREAD

**Issue by FazanaJ** [HackerN64/HackerSM64#368]
I've already actually *done* this, just making an issue so it's officially on a to-do list for a later date.

But the premise is that the number of required red coins is set when the area is loaded, rather than hardset to 8.

**Comment by Reonu** [comment]
If this is implemented it could be combined with an offset for how many you're actually required to collect

For example you could set it to 2 which means you're required to collect the amount of red coins in the level, minus 2

**Comment by gheskett** [comment]
If this can be done quickly enough, this should remain in 2.1 scope. This has a lot of potential for something like Hack of the Day.
