### ISSUE TITLE
discord is down again

### ISSUE THREAD

**Issue by Reonu** [HackerN64/HackerSM64#369]
fuck

**Comment by Reonu** [comment]
fixed by #42069

**Comment by gheskett** [comment]
i think this issue might be a bit off track, maybe check out the reonu router code and make sure that's in order first.

**Comment by Reonu** [comment]
:(

**Comment by axollyon** [comment]
![25012716_170x100](https://user-images.githubusercontent.com/20480418/160460028-fd581aa2-1552-450b-9f0f-86fedb3aef84.gif)

**Comment by gheskett** [comment]
Pog

**Comment by gheskett** [comment]
Oops I opened the invalid issue gdi
