### ISSUE TITLE
`patch_audio_bank` Crash

### ISSUE THREAD

**Issue by gheskett** [HackerN64/HackerSM64#370]
For some unknown reason, the game will sometimes (but consistently) crash on level load with a stack trace pointed to this function. The crash takes place on Thread 5 so it's not guaranteed to be an audio issue.

Changing the audio compile flags use `O2` can help mitigate this issue from popping up, but it doesn't apparently solve it for good. Most likely this is some sort of memory leak that made its way to audio data in some form, if the cause isn't part of the audio data itself.

**Comment by gheskett** [comment]
Turns out the skybox thing (while still an issue) may have been a red herring after all. This crash can apparently still happen, and can still be dodged by altering compiler optimizations. This is a pretty urgent issue (plus we're going slow enough as it is) so I'm leaving this in the scope of 2.0.2.

**Comment by Reonu** [comment]
I myself experienced this crash after having applied the skybox fix. I "fixed" it the last time by changing the audio compiler flag to `O2`, and now I "fixed" it again by changing it to `O1`.

**Comment by gheskett** [comment]
This issue reportedly may still exist, though it still has yet to pop back up in HackerSM64. I'm gonna leave this closed for now because there isn't seemingly anything we can really do about it right now anyway. The cache stuff reported in #454 is still valid, but it's unknown as to whether forcing DMA alignment actually makes any difference.
