### ISSUE TITLE
WORLD_SCALE doesn't work on the lighting engine branch

### ISSUE THREAD

**Issue by Reonu** [HackerN64/HackerSM64#377]
On the Lighting Engine branch, the game always acts as if WORLD_SCALE was 1. This makes it impossible to make big maps without triggering coordinate overflow related glitches and hangs.

**Comment by Mr-Wiseguy** [comment]
This was an issue in the matrix stack fix; the view matrix was cancelling out WORLD_SCALE rather than adjusting the camera position based on its value. Fixed in 59b423fd937f8d79ecb2f4abcff025c1ae5cb502
