### ISSUE TITLE
Investigate the use of `hot` and `cold` function attributes

### ISSUE THREAD

**Issue by Mr-Wiseguy** [HackerN64/HackerSM64#382]
The linker is allowed to reorder functions, which it can do so more intelligently with information provided by the user about which functions should be placed near each other via `hot` and `cold` attributes. The following excerpts from the GCC manual explain this in more detail:
![image](https://user-images.githubusercontent.com/68165316/165149075-a008bdd9-b376-4fab-aacb-641c22490a13.png)
![image](https://user-images.githubusercontent.com/68165316/165149090-4710ff73-19d8-4386-ad16-a833340e2610.png)

**Comment by gheskett** [comment]
Should this be ported to ultrasm64?

**Comment by gheskett** [comment]
Moved to 2.2, potentially worth closing if nobody else feels comfortable tackling this.

**Comment by gheskett** [comment]
Won't fix
