### ISSUE TITLE
Individual Music/SFX Volume Adjustments

### ISSUE THREAD

**Issue by gheskett** [HackerN64/HackerSM64#402]
Because what if terrible ear-destroying note hour-long note?

Add options for music and SFX volumes to both the file select sound options and to the pause menu. I have done stuff close to this before already so it shouldn't be too painful for me to add.

**Comment by gheskett** [comment]
Apparently a somewhat undesirable feature, closing issue.

**Comment by arthurtilly** [comment]
> 

definition of copium
