### ISSUE TITLE
Unintended shadow behavior

### ISSUE THREAD

**Issue by Lilaa3** [HackerN64/HackerSM64#404]
For some reason the shadow prioritizes the floor bellow the moving platform, changing the collision distance has no affect on the result either.
I feel like this might not be intended behavior but I can not figure out what is causing it.

HackerSM64
https://user-images.githubusercontent.com/87947656/168396306-36637ced-214f-4545-85f4-36e54350978e.mp4

Original SM64:
![image](https://user-images.githubusercontent.com/87947656/168396242-d445d621-f1b8-4559-a3b3-c351d16b1a1e.png)

**Comment by gheskett** [comment]
This is caused by auto-collision, the best solution for this is largely subjective and still up for debate.

**Comment by gheskett** [comment]
Either disable auto-collision by default or increase collision size for 2.1; A collision rework can be done for 3.0 or 3.1.

**Comment by gheskett** [comment]
Not sure if the dynamic collision PR above was a "proper" fix or just "good enough for 2.1", but I'm gonna close this in the meantime anyway.
