### ISSUE TITLE
Fall Damage Value Defines Do Not Work

### ISSUE THREAD

**Issue by gheskett** [HackerN64/HackerSM64#405]
`FALL_DAMAGE_HEIGHT_SMALL` and `FALL_DAMAGE_HEIGHT_LARGE` are not only mapped improperly, but they're complete bloat defines that really do not need to exist.

**Comment by Arceveti** [comment]
Fixed in 2.0.2

**Comment by gheskett** [comment]
Original fix was apparently already added in commit https://github.com/HackerN64/HackerSM64/commit/730f020b6d5c3bbafe0fde829fdf1dbfba787c82.
