### ISSUE TITLE
Remove COMPLETE_EN_US_SEGMENT2 define. Detect whether the assets can be extracted or not.

### ISSUE THREAD

**Issue by Reonu** [HackerN64/HackerSM64#434]
Idk if this is possible or if makefiles aren't that flexible but it would be cool. If you don't have a JP ROM, use placeholder assets. If you do have it, use the real ones. No define.

**Comment by arthurtilly** [comment]
this is going to be irrelevant once ascii is done because we decided to include the original textures in the repo. closing this prematurely because the ascii pr doesn't actually do what is described here, it just removes the need for it

**Comment by arthurtilly** [comment]
i fucked up the git hub i think
