### ISSUE TITLE
Remove possibly unnecesary defines in `config_movement.h` (discuss)

### ISSUE THREAD

**Issue by Reonu** [HackerN64/HackerSM64#436]
`SIDE_FLIP_AT_LOW_SPEEDS` this seems pointless

`NO_FALL_DAMAGE` and `NO_FALL_DAMAGE_SOUND` I think they should just be combined into a single one (what's the point of the scream if it doesn't actually warn you of fall damage)

`FALL_DAMAGE_HEIGHT_SMALL` and `FALL_DAMAGE_HEIGHT_LARGE` are a bit bloaty maybe

`SHINDOU_POLES` is this worth a define?

Feel free to discuss

**Comment by thecozies** [comment]
`EASIER_LONG_JUMPS` could be default. no reason to need a frame one ground pound. just put a comment explaining the fix

**Comment by thecozies** [comment]
`DISABLE_GROUNDPOUND_BONK`
imo enabled by default. its only painful and i dont think any other mario games have done this since

**Comment by Reonu** [comment]
I agree with both

**Comment by Reonu** [comment]
I did not mean to close that

**Comment by Reonu** [comment]
Why does github default to closing the issue when pressing ctrl+enter in the comment box

Fuck you

**Comment by thecozies** [comment]
```c
// Allows Mario to jump kick on steep surfaces that are set to be non slippery, instead of being forced to dive.
#define JUMP_KICK_FIX
```
maybe just enabled? this is a weird one

**Comment by Reonu** [comment]
`HANGING_FIX` this should be removed as well, and force it on 

with it disabled you can only grab ceilings from a single or double jump, why would you ever want that?

**Comment by thecozies** [comment]
`DISABLE_BLJ` you can search the code for "blj" and find exactly where the cause is already. most people wont disable this and if somebody really wants to AND cant figure out how, its a one line change that somebody could refer them to.

this also brings up an idea of adding comments for things and encourage people to use the search feature and read the code which would help them learn instead of having a magic toggle and not knowing what it actually does. this isn't assembly, if a noob can read it and make the change, then we dont need a define

**Comment by gheskett** [comment]
`NO_FALL_DAMAGE_SOUND` as a define doesn't need to exist, though I personally think the falling scream should be present regardless of whether fall damaged is disabled.

**Comment by gheskett** [comment]
`FALL_DAMAGE_HEIGHT_SMALL` and `FALL_DAMAGE_HEIGHT_LARGE` can probably be moved out of the global config and defined elsewhere

**Comment by MSpiller7** [comment]
`SHINDOU_POLES`
Could we include an explanation of what the differences between normal poles and Shindou poles are? This assumes the define is kept at all, but I can't comment on whether that's a good idea because I still don't know what it does 💀

**Comment by gheskett** [comment]
Current plans: https://docs.google.com/spreadsheets/d/1j2iStJFkhjGYap-t8HS9Jb2uopGK1HSUclOb2vQqzEU/edit?usp=sharing
