### ISSUE TITLE
Get rid of all inline asm in the repo

### ISSUE THREAD

**Issue by Mr-Wiseguy** [HackerN64/HackerSM64#441]
Inline asm seems to potentially cause instruction scheduling issues in GCC, so get rid of all of it. Pretty much every instance can be replaced with a GCC builtin to generate the same or similar codegen, so this isn't an issue. The `construct_float` in the mtxf_to_mtx function can remain since we know that function has correct codegen.

**Comment by gheskett** [comment]
Turns out this is important enough to warrant 2.1.

**Comment by someone2639** [comment]
absf can be removed; roundf is harder since `__bulitin_roundf` evaluates to a function call to `roundf` instead of the `round.s` instruction
