### ISSUE TITLE
Mario no longer seems to use dithering when using level warps

### ISSUE THREAD

**Issue by DarioSamo** [HackerN64/HackerSM64#473]
It seems like the dithering effect when Mario uses a warp in a level is broken and it only uses transparency instead.

Tested by building the latest commit of `master` branch.

I compared the behavior of the level warps against the 1.0 ROM. I tested in the latest Parallel Launcher using both ParaLLEl and GlideN64.

HackerSM64 ParaLLEl

https://user-images.githubusercontent.com/538504/182994220-422a835a-7f11-40f9-9608-e3634f5f033e.mp4

HackerSM64 GlideN64

https://user-images.githubusercontent.com/538504/182994226-92cd68d1-e77f-4ffa-9350-1dc8ef052b53.mp4

Vanilla ParaLLEl

https://user-images.githubusercontent.com/538504/182994212-519b6fa1-cb66-42e4-a5c2-ac7aed7c6091.mp4

Vanilla GlideN64

https://user-images.githubusercontent.com/538504/182994217-1abf26bf-a6a3-4dc1-8232-88bba303fecf.mp4

**Comment by thecozies** [comment]
how the hell did we miss this lmao
