### ISSUE TITLE
Add cmake support

### ISSUE THREAD

**Issue by WSLUser** [HackerN64/HackerSM64#482]
Currently this project can only be built from gcc. I'd like to request the ability to compile from cmake as well. Cmake provides the best optimizations in any benchmarks ever run even up to this year over any other compiler (gcc, MSVC, etc.) so getting this support could potentially boost the performance in addition to providing another compiling option.

**Comment by arthurtilly** [comment]
Modern compiler optimizations do not necessarily boost N64 performance and often harm it as N64 architecture is very different from modern machines, so even if a different compiler performs better in modern benchmarks there is no guarantee it will perform better on the N64. Additionally, a large amount of research has already gone into figuring out which compiler flags to pass to GCC to maximise N64 performance which would be lost if a new compiler was added. It is simply not worth the effort to add or maintain.

**Comment by someone2639** [comment]
cmake is not a compiler.....

also the build system has 0 (and i mean 0) use for any "features" cmake has. we don't link any libraries, and we don't build an exe.
