### ISSUE TITLE
Memory leak when switching between levels using debug level select

### ISSUE THREAD

**Issue by AloXado320** [HackerN64/HackerSM64#496]
While i was testing levels, the game crashed when i entered a level like a 10th time

This only happens when using debug level select as warping between areas is fine

My guess is that because how level selects loads levels, it doesn't clear collision pools properly? See `MEM` value below

https://user-images.githubusercontent.com/38191089/192422074-cfa00412-f11b-40fe-9a8d-cedfb3fda2d2.mp4

**Comment by gheskett** [comment]
Nice find
