### ISSUE TITLE
Failure to install dependencies

### ISSUE THREAD

**Issue by TheMingo888** [HackerN64/HackerSM64#581]
I've followed the steps in the wiki to the point of [installing dependencies](https://github.com/HackerN64/HackerSM64/wiki/Installing-Dependencies), but Ubuntu is not succeeding in getting all of them, resulting in `make` and `gcc` not being installed properly.

It looks like this is the error:
`E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_5.15.0-56.62_amd64.deb  404  Not Found [IP: 185.125.190.36 80]`

I tried again with `--fix-missing`, which worked a little bit, but it produced the same error eventually and `linux/limits.h` seemed to be missing.

https://pastebin.com/XzHGqSV7

**Comment by Reonu** [comment]
did you run `sudo apt update` before trying to install stuff

**Comment by TheMingo888** [comment]
Yep. Also `sudo apt upgrade`, though it had nothing to do.

**Comment by gheskett** [comment]
This does not appear to be an issue with HackerSM64 itself. If you need help troubleshooting stuff like this, please feel free to join the Discord and ask there!
