### ISSUE TITLE
Freeze (no crash screen) when debug free moving in HMC

### ISSUE THREAD

**Issue by Arceveti** [HackerN64/HackerSM64#599]
![image](https://user-images.githubusercontent.com/73617174/224418442-5c0d5313-4576-4134-aa12-f3c5f84978a7.png)
![image](https://user-images.githubusercontent.com/73617174/224418520-347a9613-86f3-4c5f-817b-c57c0eba5ceb.png)

Confirmed on console and ParaLLEl.

**Comment by thecozies** [comment]
I didn't add the flag to any objects, we can decide some for later but out of scope for this PR imo
