### ISSUE TITLE
Wet Dry World Crashes on Entry

### ISSUE THREAD

**Issue by gheskett** [HackerN64/HackerSM64#615]
Potentially related to the (removal of) denorm checks when vanilla level checks are disabled (the game does not crash with them turned on). Does not crash with Parallel Launcher.

![image](https://user-images.githubusercontent.com/22061597/232335993-291b445a-4c2c-4415-8f15-790f585fabde.png)

**Comment by AloXado320** [comment]
I feel like norm check should be essential given that WDW and some ROM Hacks had this issue creating odd vertices with a norm of 0, recall that without the NULL check (and forcing a norm value) you get flattened odd vertices, causing some invisible walls or floors.
https://cdn.discordapp.com/attachments/926163673112784947/1033552225559121941/unknown.png

Here's me printing the coordinates of the same odd vertices shown above:
https://cdn.discordapp.com/attachments/910581195891413002/1097259336608264252/image.png
