### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Darkpepito** [HackerN64/HackerSM64#641]
Hello,
I am interested into making romhacks, but I'm not able to compile this project with `make`.  
Here is the error log :
```src/game/mario_actions_moving.c: In function ‘update_walking_speed’:
src/game/mario_actions_moving.c:440:50: error: ‘dividor’ undeclared (first use in this function)
  440 |         m->forwardVel += (1.1f - m->forwardVel / dividor);
      |                                                  ^~~~~~~
src/game/mario_actions_moving.c:440:50: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:818 : build/us_n64/src/game/mario_actions_moving.o] Error 1
```
My gcc version :
```gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0```

Other system infos :  
```  
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: c86d35c6ea5f47a092e0fb3750d381eb
           Boot ID: ee06e73cb974420a850c0a77850e2821
  Operating System: Zorin OS 16.2
            Kernel: Linux 5.15.0-75-generic
      Architecture: x86-64
```

I am really sorry to take your time for a surely stupid error.  
Thank you !

**Comment by gheskett** [comment]
This looks to me like user error. This issue board is for developments to the base HackerSM64 repository, and not for issues with personal hacks. If you need help, please feel free ask for it inside the HackerSM64 Discord server. :)

**Comment by Darkpepito** [comment]
Okay really sorry !
