### ISSUE TITLE
If you see E: Unable to locate package (name)

### ISSUE THREAD

**Issue by WinHack9702GitHub** [HackerN64/HackerSM64#659]
type command `sudo apt update` then try again

**Comment by WinHack9702GitHub** [comment]
On Ubuntu

**Comment by gheskett** [comment]
Hello, this issue board is for reporting issues with the HackerSM64 repository itself. Any issues you have that aren't the responsibility of HackerSM64, feature suggestions, or any advice should ideally be relayed in the Discord server instead. :)
