### ISSUE TITLE
HMC Crash

### ISSUE THREAD

**Issue by Arceveti** [HackerN64/HackerSM64#66]
Loading into HMC via debug level select causes a crash in HANDLE_DP_COMPLETE, where sCurrentDisplaySPTask is NULL.
The intro demo HMC section also freezes, but with no crash screen.

There are several "half-fixes", such as null checking sCurrentDisplaySPTask, or increasing the number in alloc_display_list in geo_process_background from 7 to 8, and a few others. However, these "half-fixes" cause major flickering after entering another level after HMC, and cause HMC's starting screen transition to be delayed for 1 or 2 frames:

[Frame 1](https://i.imgur.com/vxBi2eL.png)

[Frame 2](https://i.imgur.com/KOemoiK.png)

It may potentially be caused by there being too many objects on screen on frame 1, before the level geometry itself loads.

The crash also does not happen if the camera starts at a different angle than normal.

Removing some macro objects or increasing GFX_POOL_SIZE fixes it without the flickering issues, but it would be better to fix the underlying problem.

**Comment by gheskett** [comment]
Closing until when/if this issue resurfaces, as I'm not sure it's valid anymore
