### ISSUE TITLE
Downwarp fix prevents fading warps from dropping to floor

### ISSUE THREAD

**Issue by Mineqwerty** [HackerN64/HackerSM64#673]
pretty easy hardcoded fix, just putting it here so i dont forget

**Comment by gheskett** [comment]
Make sure btw to run through everything that calls the function with the downwarp fix and determine whether it could benefit from dropping Mario to the floor.

**Comment by Mineqwerty** [comment]
will do, the only other thing i can maybe think of is door warps

**Comment by thecozies** [comment]
I think we should tackle this as an individual issue at first and create a separate issue for investigation into other potential cases. when fading into a warp you'd just use marios initial floor height making it a simple action specific change. requiring this issue to take on the rest of potential issues will likely result in another 3 months of 2.1 dev vs something easily digestible by people with limited free time

**Comment by Mineqwerty** [comment]
simple fix, but i agree cozies. we can do a more thorough investigation down the line
