### ISSUE TITLE
Update to latest UNFLoader

### ISSUE THREAD

**Issue by buu342** [HackerN64/HackerSM64#729]
Hiya, I noticed that the UNFLoader section says that:
```
NOTE: Closing the UNFLoader window will result in your game eventually hanging due to lacking a USB device to send messages to, so beware of that
```
This has not been true since Version 1.5, released in April. So that means that your UNFLoader library is quite old and will likely have problems with up-to-date UNFLoader (including with alternative tools like g64drive) due to changes in the USB protocol. Would be a good idea to update your libraries!

Also, the latest UNFLoader has GDB support, which while not super complete (it doesn't handle overlays, which SM64 will probably uses? I don't know much about SM64 tbh :v ) might be useful for some.

**Comment by gheskett** [comment]
We updated UNFLoader to support 1.5 back in May actually, so this is just another matter of the README being severely dated. With that said, we're aware of the new GDB support and plan to hopefully look into that soon!

**Comment by buu342** [comment]
Great to hear! :slightly_smiling_face:

**Comment by gheskett** [comment]
Moving to 2.2 (still important)

**Comment by buu342** [comment]
Awesome, now you just gotta update the readme to remove this line:
> NOTE: Closing the UNFLoader window will result in your game eventually hanging due to lacking a USB device to send messages to, so beware of that
