### ISSUE TITLE
error 0x800f080c ?

### ISSUE THREAD

**Issue by Mrmaxidepapel** [HackerN64/HackerSM64#741]
I was literally doing the first step, I did everything right, I opened the Windows terminal as administrator and it just says *Error: 0x800f080c*, is there any solution?

<img width="134" alt="image" src="https://github.com/HackerN64/HackerSM64/assets/143361819/5aeaea5d-0871-444f-85ac-fc312a3d6627">

**Comment by gheskett** [comment]
Hello, this issue board is for reporting issues with the HackerSM64 repository itself. Any issues you have that aren't the responsibility of HackerSM64, feature suggestions, or any advice should ideally be relayed in the HackerN64 Discord server instead. :)
