### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by aaethern** [HackerN64/HackerSM64#826]
Hi, I'm having an error with compiling,

Whenever I try to run the command `git clone https://github.com/HackerN64/HackerSM64.git <name of my project>` it finishes enumerating objects, counting objects, and compressing objects, but when it tries to receive objects it gets stuck at 15-50%, fails, and then everything else fails.
It failed 3 times, these are the 3 types of errors:

`Cloning into <project name>`
`remote: Enumerating objects: 100% (552/552), done.`
`remote: Counting objects: 100% (236/236), done.`
`remote: Compressing objects: 100% (236/236), done.`
`error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.`
`error 2863 bytes of body are still expected`
`fetch-pack: unexpected disconnect while reading sideband packet`
`fatal: early EOF`
`fatal: fetch-pack: invalid-pack output`

`Cloning into <project name>`
`remote: Enumerating objects: 100% (552/552), done.`
`remote: Counting objects: 100% (236/236), done.`
`remote: Compressing objects: 100% (236/236), done.`
`error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.`
`error 4408 bytes of body are still expected`
`fetch-pack: unexpected disconnect while reading sideband packet`
`fatal: early EOF`
`fatal: fetch-pack: invalid-pack output`

`Cloning into <project name>`
`remote: Enumerating objects: 100% (552/552), done.`
`remote: Counting objects: 100% (236/236), done.`
`remote: Compressing objects: 100% (236/236), done.`
`error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)`
`error 5835 bytes of body are still expected`
`fetch-pack: unexpected disconnect while reading sideband packet`
`fatal: early EOF`
`fatal: fetch-pack: invalid-pack output`

I would appreciate it if you could help me :)

**Comment by gheskett** [comment]
This appears to be an issue with Ubuntu or something else that isn't HackerSM64 related. This issue board is for reporting legitimate issues with HackerSM64 itself. If you need help, please feel free to reach out in the [HackerN64 discord server](https://discord.gg/brETAakcXr).
