### ISSUE TITLE
dist_between_objects

### ISSUE THREAD

**Issue by Retro-Hax** [HackerN64/HackerSM64#97]
So after alot of testing it seems like Koopa The Quick and Big Penguin Races cause crashes on Console aswell as Emulators (Project 64, Paralell 64 & Mupen64Plus Next)

It only happens when adding modifying those Trajectories i only have tested those cases tho dont know about Metal Balls and other Trajectories of that sort also it happens both in Debug and Normal Mode (aka when debug mode is disabled)

Here are also some Screenschots of the Crash Screen:
![image](https://user-images.githubusercontent.com/69952967/139537788-d20ea04b-e116-4f7d-8c0b-5616c0822604.png)
![image](https://user-images.githubusercontent.com/69952967/139537803-1c49a9eb-9c8d-464d-a778-2ecde8b3412e.png)

it seems to be because obj1 and/or obj2 is NULL

**Comment by Reonu** [comment]
i'm gonna assume this is skill issue

**Comment by gheskett** [comment]
This is also an old issue, but has anybody actually tried to replicate it?
